### ISSUE TITLE
Choose Folder option in flow does not work.

### ISSUE THREAD

**Issue by sveken** [cwilby/nextcloud-workflow-media-converter#409]
## Steps to reproduce
1. Create flow for media conversion
2. Choose any of the move options like after output is ready "Move output to specific folder"
3. The "choose folder" option does not do anything/open any picker

### Expected behaviour
The choose folder picker should pop up or some form of text field to enter path

### Actual behaviour
Nothing happens.

## Workflow Media Converter app

**Workflow Media Converter app version:** (see apps admin page: `/index.php/settings/apps`)
1.9.0

## Server configuration

**Operating system**: Ubuntu/RedHat/...
Truenas Scale/ Debian

**Web server:** Apache/Nginx
Nginx
**Database:** MySQL/Maria/SQLite/PostgreSQL
PostgresSQL

**PHP version:**
8.2.14

**Nextcloud Version:** (see admin page)
28.0.1

**Where did you install Nextcloud from:**
Truecharts Catalogue 

**Signing status:**

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```
No errors have been found.

**List of activated apps:**
Activity
Announcment Center
Automated Media Conversion
Brute-force Settings
Calender
Camera RAW Previews
Circles
CLient Push
Collaborative Tags
Comments
Configurable share links
Contacts
Contacts interaction
Dashboard
Deck
Deleted files
End-end encryption
excalidraw integration 
External Storage 
Federation
FIle remidners
File sharing
FIle automated Tagging
First run wiz
Forms
Guests
Log Reader
Memories
Monitoring
Nextcloud Announcments
Nextcloud Office
Notes
Notications
PAssword Policy
Passwords
Passwords  andbook
PDF Viewer
PhoneTrack
Photos
Polls
Preview Generator
Privacy
Recongize
Reccomendations
Registration
Related Resources
Share by Mail
Support
talk
Tasks
text
2FA TOPP Provider 
2FA Webauthn
Usage Survey
Update Notication
User Status
Versions
Weather Status

**Comment by sveken** [comment]
I have just tried in firefox, Chrome, and edge, also in incognito. 
Also tried Chrome on my phone via cell connection. Behavior stays the same.

**Comment by Misls** [comment]
Same behavior here with the following setup:

Ubuntu Server 22.04 LTS
Nextcloud version 27.1.5
PHP version 8.1.27
MySQL version 10.6.12
Apache 2.4

Also tried different browsers (chrome, firefox) with different browser protection setups without effect on the "Choose Folder" Button

**Comment by printplaatreparatie** [comment]
I think it might have something to do with the fact that my/our Nextcloud installation is in a in a directory, and not directly in the index domainname (eg. example.com/nextcloud). Here are my browser logs:

```
You need to fill either the text or the ariaLabel props in the button component.
Object { text: undefined, ariaLabel: null }

Object { _uid: 6, _isVue: true, __v_skip: true, _scope: {…}, "$options": {…}, _renderProxy: {…}, _self: {…}, "$parent": {…}, "$root": {…}, "$children": [], … }
workflow_media_converter-personalSettings.js:2:701499
Loading failed for the <script> with source “https://[REDACTED]/apps/workflow_media_converter/js/workflow_media_converter-vendors-node_modules_path-browserify_index_js-node_modules_nextcloud_dialogs_dist_chunks_Dial-7228d0.js?v=5959475e462b19fc49c0”. workflow_media_converter:1:1
Loading failed for the <script> with source “https://[REDACTED]/apps/workflow_media_converter/js/workflow_media_converter-node_modules_nextcloud_dialogs_dist_legacy_mjs.js?v=a5e97bb3a2cce054c0bb”. workflow_media_converter:1:1
Content-Security-Policy: The page’s settings blocked the loading of a resource at https://[REDACTED]/apps/workflow_media_converter/js/workflow_media_converter-vendors-node_modules_path-browserify_index_js-node_modules_nextcloud_dialogs_dist_chunks_Dial-7228d0.js?v=5959475e462b19fc49c0 (“script-src”). workflow_media_converter-personalSettings.js:2:663869
ChunkLoadError: Loading chunk vendors-node_modules_path-browserify_index_js-node_modules_nextcloud_dialogs_dist_chunks_Dial-7228d0 failed.
(error: https://[REDACTED]/apps/workflow_media_converter/js/workflow_media_converter-vendors-node_modules_path-browserify_index_js-node_modules_nextcloud_dialogs_dist_chunks_Dial-7228d0.js?v=5959475e462b19fc49c0)
    j https://[REDACTED]/nextcloud/apps/workflow_media_converter/js/workflow_media_converter-personalSettings.js?v=72f01f5b-40:2
    e https://[REDACTED]/nextcloud/apps/workflow_media_converter/js/workflow_media_converter-personalSettings.js?v=72f01f5b-40:2
    e https://[REDACTED]/nextcloud/apps/workflow_media_converter/js/workflow_media_converter-personalSettings.js?v=72f01f5b-40:2
    pick https://[REDACTED]/nextcloud/apps/workflow_media_converter/js/workflow_media_converter-personalSettings.js?v=72f01f5b-40:2
    t https://[REDACTED]/nextcloud/apps/workflow_media_converter/js/workflow_media_converter-personalSettings.js?v=72f01f5b-40:2
    c https://[REDACTED]/nextcloud/apps/workflow_media_converter/js/workflow_media_converter-personalSettings.js?v=72f01f5b-40:2
    F https://[REDACTED]/nextcloud/apps/workflow_media_converter/js/workflow_media_converter-personalSettings.js?v=72f01f5b-40:2
    N https://[REDACTED]/nextcloud/apps/workflow_media_converter/js/workflow_media_converter-personalSettings.js?v=72f01f5b-40:2
    Ws https://[REDACTED]/nextcloud/apps/workflow_media_converter/js/workflow_media_converter-personalSettings.js?v=72f01f5b-40:2
    i https://[REDACTED]/nextcloud/apps/workflow_media_converter/js/workflow_media_converter-personalSettings.js?v=72f01f5b-40:2
    openFilePicker https://[REDACTED]/nextcloud/apps/workflow_media_converter/js/workflow_media_converter-personalSettings.js?v=72f01f5b-40:2
    openFilePicker https://[REDACTED]/nextcloud/apps/workflow_media_converter/js/workflow_media_converter-personalSettings.js?v=72f01f5b-40:2
    openFilePicker https://[REDACTED]/nextcloud/apps/workflow_media_converter/js/workflow_media_converter-personalSettings.js?v=72f01f5b-40:2
    click https://[REDACTED]/nextcloud/apps/workflow_media_converter/js/workflow_media_converter-personalSettings.js?v=72f01f5b-40:2
    Cs https://[REDACTED]/nextcloud/apps/workflow_media_converter/js/workflow_media_converter-personalSettings.js?v=72f01f5b-40:2
    s https://[REDACTED]/nextcloud/apps/workflow_media_converter/js/workflow_media_converter-personalSettings.js?v=72f01f5b-40:2
    _wrapper https://[REDACTED]/nextcloud/apps/workflow_media_converter/js/workflow_media_converter-personalSettings.js?v=72f01f5b-40:2
workflow_media_converter-personalSettings.js:2:231421
Content-Security-Policy: The page’s settings blocked the loading of a resource at https://[REDACTED]/apps/workflow_media_converter/js/workflow_media_converter-node_modules_nextcloud_dialogs_dist_legacy_mjs.js?v=a5e97bb3a2cce054c0bb (“script-src”). workflow_media_converter-personalSettings.js:2:663869
GET
https://[REDACTED]/nextcloud/apps/theming/image/logo?v=40
[HTTP/2 404  920ms]

GET
https://[REDACTED]/nextcloud/apps/theming/image/logo?v=40
[HTTP/2 404  630ms]

```

**Comment by printplaatreparatie** [comment]
Note that the failed command is trying to fetch a resource from `domainname.example/apps` instead of 'domainname.example/nextcloud/apps'

**Comment by sveken** [comment]
My nextcloud is installed at the root of the domain, and I still have this issue.

**Comment by printplaatreparatie** [comment]
Are there helpful logs [that you can share?](https://support.shortpoint.com/support/solutions/articles/1000222881-save-browser-console-file)

**Comment by sveken** [comment]
[mediaconvert-1706132819743.log](https://github.com/cwilby/nextcloud-workflow-media-converter/files/14043983/mediaconvert-1706132819743.log)
Here we go. Seems to be 404ing on the button.

**Comment by printplaatreparatie** [comment]
The button stopped working in my setup somewhere after Dec. 12th, 2023. It still worked when I did some tests for [this](https://github.com/cwilby/nextcloud-workflow-media-converter/issues/397#issuecomment-1851998283) reply.

**Comment by n0paleon** [comment]
I think the problem is with writing /apps/ in the url path, shouldn't it be /custom_apps/? I tried accessing it manually, the requested js file can be accessed normally

**Comment by printplaatreparatie** [comment]
Not for me. It has definitely something to do with referring to the root folder. I can reach `https://domainname.example/nextcloud/apps/workflow_media_converter/js/workflow_media_converter-node_modules_nextcloud_dialogs_dist_chunks_index-xxxxx_mjs.js` but the button directs to `https://domainname.example/apps/workflow_media_converter/js/workflow_media_converter-node_modules_nextcloud_dialogs_dist_chunks_index-xxxxx_mjs.js'.`

**Comment by mmuman** [comment]
I installed this to test converting stuff for some DLNA setup but I found this bug… Oddly Chromium gives more info than Firefox which only mentions CSP as a reason for the block:

```
workflow_media_converter-personalSettings.js?v=f505562d-0:2 Refused to load the script 'https://[domain]/apps/workflow_media_converter/js/workflow_media_converter-node_modules_nextcloud_dialogs_dist_chunks_index-csK3cpe5_mjs.js?v=bc706ee6becf1a314d5a' because it violates the following Content Security Policy directive: "script-src 'nonce-L3d5QVRYNnNRU1FDb0tuTSsyOXJkenBBTVNaSnBvMDA5R29TdnNIYzFVND06emp2ckNqTFBObFpMbVoraXlUNG5JVk16WmtnUjN1cHhoUVZma2FMcCtqcz0='". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

r.l @ workflow_media_converter-personalSettings.js?v=f505562d-0:2
```

Does the script need to be declared in some way to the core to get that nonce forwarded or something?

**Comment by mmuman** [comment]
So from what I understand `personalSettings.js` attemps to load this `…chunks_index….js` without passing around that nonce that itself was loaded with, when the CSP forbids that.

Could it be we just need a [--no-unsafe-inline](https://stackoverflow.com/questions/58397934/are-we-forced-to-use-unsafe-inline-in-our-csp-when-using-vue-js) arg to npm!?

I don't even know how people are supposed to build this, there's nothing in the README about that… and no `./configure` :-P

**Comment by mmuman** [comment]
Ohhh, a Makefile :heart_eyes:

**Comment by mmuman** [comment]
Still no idea where to fix that though…

**Comment by mmuman** [comment]
Got a fix \o/

**Comment by mmuman** [comment]
All these hours for a oneliner :tired_face:

**Comment by sveken** [comment]
[mediaconvert-log.log](https://github.com/cwilby/nextcloud-workflow-media-converter/files/14828816/mediaconvert-log.log)
Installed the update today and still no change on my end.
Tried restarting the container after the update, cleared browser cache.

**Comment by printplaatreparatie** [comment]
Same here, @cwilby please reopen this issue.

**Comment by mmuman** [comment]
Are you using HTTP or a properly configured HTTPS server?

**Comment by printplaatreparatie** [comment]
HTTPS

**Comment by mmuman** [comment]
Maybe the NC version ? Here I'm using 27.1.2…

**Comment by cwilby** [comment]
Kind of staring into a black box on this one.  I'm pushing a change to the build script, it may be that the dev build is being released instead of the production build.

**Comment by sveken** [comment]
Im using HTTPS and 28.0.3

**Comment by oliut** [comment]
Nextcloud 28.0.4 (docker/apache) workflow-media-converter 1.10.3 with ssl offload on nginx
(restart container, remove - reinstall media converter - does not help)

settings/user/workflow_media_converter

Choose folder button do  not work with Error (in Chrome)

https://[my-server]/custom_apps/workflow_media_converter/workflow_media_converter-node_modules_nextcloud_dialogs_dist_chunks_index-RkOaxczZ_mjs.js?v=b503adf395d4b1c57cc4

Request Method: GET Status Code: 404 Not Found

Same in Edge

    at r.f.j (workflow_media_converter-personalSettings.js?v=2dc04f56-22:2:943334)
    at workflow_media_converter-personalSettings.js?v=2dc04f56-22:2:941562
    at Array.reduce (<anonymous>)
    at r.e (workflow_media_converter-personalSettings.js?v=2dc04f56-22:2:941540)
    at y.pick (workflow_media_converter-personalSettings.js?v=2dc04f56-22:2:946409)
    at workflow_media_converter-personalSettings.js?v=2dc04f56-22:2:961784
    at v (workflow_media_converter-personalSettings.js?v=2dc04f56-22:2:955504)
    at Generator.<anonymous> (workflow_media_converter-personalSettings.js?v=2dc04f56-22:2:956846)
    at Generator.next (workflow_media_converter-personalSettings.js?v=2dc04f56-22:2:955933)
    at X (workflow_media_converter-personalSettings.js?v=2dc04f56-22:2:961407)
    
    nginx log
    
[03/Apr/2024:11:29:12 +0300] "GET /custom_apps/workflow_media_converter/workflow_media_converter-node_modules_nextcloud_dialogs_dist_chunks_index-RkOaxczZ_mjs.js?v=b503adf395d4b1c57cc4 HTTP/2.0" 404 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"

**Comment by mmuman** [comment]
Oh I didn't notice you were using a flow, I never actually tried before. Still I just tried creating one and it works here.

**Comment by mmuman** [comment]
I don't get where this "custom_apps" is used, I have no URL with that loaded anywhere when I use it…

**Comment by oliut** [comment]
/custom_apps/ is the second app folder that is writable. if I reinstall workflow-media-converter in /apps/ folder - error (button not work) stays the same. And some previous versions of  workflow-media-converter (1.9.3) I was able to "fix" by moving it from custom_apps to apps. but for current version (1.10.3)  this workaround not work any more.

**Comment by barrettsoftware** [comment]
I am also experiencing this issue on a new deployment of an LXC container.

**Comment by oliut** [comment]
`cp /var/www/html/apps/workflow_media_converter/js/*.js /var/www/html/apps/workflow_media_converter/`

workaround for v1.10.3 that makes button work for me

**Comment by printplaatreparatie** [comment]
@oliut This works for me as well, nice!

Note that the problem with the web root [described here](https://github.com/cwilby/nextcloud-workflow-media-converter/issues/409#issuecomment-2003437599) was already solved with one of the last updates.

**Comment by barrettsoftware** [comment]
> `cp /var/www/html/apps/workflow_media_converter/js/*.js /var/www/html/apps/workflow_media_converter/`
> 
> workaround for v1.10.3 that makes button work for me

this fix worked for me after I edited the paths to match my environment

**Comment by sveken** [comment]
Just updated to NC29 Issue persists.

**Comment by AlexandruNegura** [comment]
So for this issue I did the following on an AIO instalation:

1. Moved the app from 'custom_apps' folder to 'apps' folder using:
```mv /var/www/html/custom_apps/workflow_media_converter /var/www/html/apps/workflow_media_converter```
2. Copy the JS files as in the answer above:
```cp /var/www/html/apps/workflow_media_converter/js/*.js /var/www/html/apps/workflow_media_converter/```

**Comment by cwilby** [comment]
Fixed, needed to set `__webpack_public_path__` correctly. (See above commit)
This fixed the file picker issue on my Nextcloud instance, which has been having this same issue.
It should also solve for people who install via the app store or install it directly into custom_apps etc.

**Comment by sveken** [comment]
This has fixed the file picker for the batch conversion area. 
However the folder select still does not work when configuring a flow with media converter. 
For example a flow that moves the source to a specific folder after run etc. 
![image](https://github.com/cwilby/nextcloud-workflow-media-converter/assets/19641755/cfd522ea-4bc5-4be6-8716-f9923e1d12ca)

**Comment by cwilby** [comment]
How can a platform be both under and over documented

**Comment by cwilby** [comment]
@sveken - Also needed to apply the above fix to the flow operator.  Released in v1.11.7, please re-test and let me know if it isn't resolved.

**Comment by sveken** [comment]
Thank you. 
V1.11.7 fixes flow as well.
